import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc.js';
import timezone from 'dayjs/plugin/timezone.js';
import { ChatProfile, VaccineSchedule, DailyRoutine, Feeding, SleepSession } from '../database/models/index.js';
import { VACCINATION_SCHEDULE, DAILY_SCHEDULE_BY_AGE } from '../config/index.js';

dayjs.extend(utc);
dayjs.extend(timezone);

const VIETNAM_TZ = 'Asia/Ho_Chi_Minh';

/**
 * Tạo lịch tiêm chủng tự động theo ngày sinh
 * Tạo TẤT CẢ vaccine từ bây giờ trở đi + vaccine quá hạn trong 30 ngày
 */
export const generateVaccinationSchedule = async (chatId, dateOfBirth) => {
  try {
    const birthDate = dayjs.tz(dateOfBirth, VIETNAM_TZ);
    const today = dayjs.tz(dayjs(), VIETNAM_TZ);
    
    console.log(`[VaccineSchedule] Tạo lịch tiêm cho chatId=${chatId}`);
    console.log(`[VaccineSchedule] Ngày sinh: ${birthDate.format('YYYY-MM-DD')}`);
    console.log(`[VaccineSchedule] Hôm nay: ${today.format('YYYY-MM-DD')}`);
    
    // Xóa lịch tiêm cũ đã auto-generate
    const deleted = await VaccineSchedule.deleteMany({ chatId, autoGenerated: true });
    console.log(`[VaccineSchedule] Đã xóa ${deleted.deletedCount} lịch cũ`);
    
    const schedules = [];
    
    for (const vaccine of VACCINATION_SCHEDULE) {
      // Tính ngày tiêm
      let vaccineDate;
      if (vaccine.ageDays !== undefined) {
        vaccineDate = birthDate.add(vaccine.ageDays, 'day');
      } else {
        vaccineDate = birthDate.add(vaccine.ageMonths, 'month');
      }
      
      // Tạo lịch cho vaccine:
      // - Tất cả vaccine trong tương lai
      // - Vaccine quá hạn trong vòng 30 ngày (để user có thể đánh dấu đã tiêm)
      const cutoffDate = today.subtract(30, 'day');
      
      if (vaccineDate.isAfter(cutoffDate)) {
        schedules.push({
          chatId,
          vaccineName: vaccine.name,
          date: vaccineDate.toDate(),
          ageMonths: vaccine.ageMonths || 0,
          ageDays: vaccine.ageDays,
          required: vaccine.required,
          autoGenerated: true,
          recurring: vaccine.recurring || false,
          completed: false
        });
        console.log(`[VaccineSchedule] + ${vaccine.name} → ${vaccineDate.format('YYYY-MM-DD')}`);
      }
    }
    
    // Lưu vào database
    if (schedules.length > 0) {
      await VaccineSchedule.insertMany(schedules);
      console.log(`[VaccineSchedule] ✅ Đã tạo ${schedules.length} mũi tiêm`);
    } else {
      console.log(`[VaccineSchedule] ⚠️ Không có mũi tiêm nào cần tạo`);
    }
    
    return schedules.length;
  } catch (error) {
    console.error('[VaccineSchedule] ❌ Lỗi:', error);
    throw error;
  }
};

/**
 * Lấy lịch ăn/ngủ theo độ tuổi
 */
export const getScheduleByAge = (ageMonths) => {
  const schedule = DAILY_SCHEDULE_BY_AGE.find(
    s => ageMonths >= s.minMonths && ageMonths < s.maxMonths
  );
  return schedule || DAILY_SCHEDULE_BY_AGE[0];
};

/**
 * Tạo lịch ăn/ngủ hàng ngày cho bé
 */
export const generateDailyRoutine = async (chatId) => {
  const profile = await ChatProfile.findOne({ chatId });
  if (!profile?.dateOfBirth) return null;
  
  const now = dayjs.tz(dayjs(), VIETNAM_TZ);
  const today = now.startOf('day');
  const birthDate = dayjs.tz(profile.dateOfBirth, VIETNAM_TZ);
  const ageMonths = now.diff(birthDate, 'month');
  
  // Lấy lịch theo độ tuổi
  const scheduleTemplate = getScheduleByAge(ageMonths);
  
  // Kiểm tra đã có lịch hôm nay chưa
  let routine = await DailyRoutine.findOne({
    chatId,
    date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() }
  });
  
  if (!routine) {
    // Tạo lịch mới
    routine = new DailyRoutine({
      chatId,
      date: today.toDate(),
      ageMonths,
      feedingIntervalHours: scheduleTemplate.feedingIntervalHours,
      totalSleepRecommended: scheduleTemplate.totalSleep,
      feedingSchedule: scheduleTemplate.feeds.map(time => ({
        time,
        completed: false,
        missed: false,
        reminded: false
      })),
      sleepSchedule: scheduleTemplate.sleeps.map(sleep => ({
        name: sleep.name,
        startTime: sleep.start,
        duration: sleep.duration,
        completed: false,
        missed: false,
        reminded: false
      }))
    });
    await routine.save();
  }
  
  return routine;
};

/**
 * Cập nhật thời gian ăn thực tế
 */
export const updateFeedingTime = async (chatId, scheduledTime, actualTime, amountMl) => {
  const today = dayjs.tz(dayjs(), VIETNAM_TZ).startOf('day');
  
  const result = await DailyRoutine.findOneAndUpdate(
    {
      chatId,
      date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() },
      'feedingSchedule.time': scheduledTime
    },
    {
      $set: {
        'feedingSchedule.$.completed': true,
        'feedingSchedule.$.actualTime': actualTime,
        'feedingSchedule.$.amountMl': amountMl
      }
    },
    { new: true }
  );
  
  return result;
};

/**
 * Cập nhật thời gian ngủ thực tế
 */
export const updateSleepTime = async (chatId, sleepName, actualStart, actualEnd, actualDuration) => {
  const today = dayjs.tz(dayjs(), VIETNAM_TZ).startOf('day');
  
  const result = await DailyRoutine.findOneAndUpdate(
    {
      chatId,
      date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() },
      'sleepSchedule.name': sleepName
    },
    {
      $set: {
        'sleepSchedule.$.completed': true,
        'sleepSchedule.$.actualStart': actualStart,
        'sleepSchedule.$.actualEnd': actualEnd,
        'sleepSchedule.$.actualDuration': actualDuration
      }
    },
    { new: true }
  );
  
  return result;
};

/**
 * Kiểm tra và tìm các bữa ăn/giấc ngủ bị bỏ lỡ
 */
export const checkMissedActivities = async (chatId) => {
  const now = dayjs.tz(dayjs(), VIETNAM_TZ);
  const today = now.startOf('day');
  const currentTime = now.format('HH:mm');
  
  const routine = await DailyRoutine.findOne({
    chatId,
    date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() }
  });
  
  if (!routine) return { missedFeeds: [], missedSleeps: [] };
  
  const missedFeeds = [];
  const missedSleeps = [];
  
  // Kiểm tra bữa ăn bị lỡ (quá 30 phút so với lịch)
  for (const feed of routine.feedingSchedule) {
    if (!feed.completed && !feed.reminded && feed.time < currentTime) {
      const scheduledTime = dayjs.tz(`${today.format('YYYY-MM-DD')} ${feed.time}`, VIETNAM_TZ);
      const diff = now.diff(scheduledTime, 'minute');
      if (diff >= 30 && diff <= 120) { // 30 phút - 2 tiếng sau lịch
        missedFeeds.push({
          time: feed.time,
          minutesLate: diff
        });
      }
    }
  }
  
  // Kiểm tra giấc ngủ bị lỡ
  for (const sleep of routine.sleepSchedule) {
    if (!sleep.completed && !sleep.reminded && sleep.startTime < currentTime) {
      const scheduledTime = dayjs.tz(`${today.format('YYYY-MM-DD')} ${sleep.startTime}`, VIETNAM_TZ);
      const diff = now.diff(scheduledTime, 'minute');
      if (diff >= 30 && diff <= 120) {
        missedSleeps.push({
          name: sleep.name,
          time: sleep.startTime,
          minutesLate: diff
        });
      }
    }
  }
  
  return { missedFeeds, missedSleeps };
};

/**
 * Đánh dấu đã nhắc nhở
 */
export const markAsReminded = async (chatId, type, identifier) => {
  const today = dayjs.tz(dayjs(), VIETNAM_TZ).startOf('day');
  
  if (type === 'feeding') {
    await DailyRoutine.findOneAndUpdate(
      {
        chatId,
        date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() },
        'feedingSchedule.time': identifier
      },
      { $set: { 'feedingSchedule.$.reminded': true } }
    );
  } else if (type === 'sleep') {
    await DailyRoutine.findOneAndUpdate(
      {
        chatId,
        date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() },
        'sleepSchedule.name': identifier
      },
      { $set: { 'sleepSchedule.$.reminded': true } }
    );
  }
};

/**
 * Sửa giờ bắt đầu ăn hoặc ngủ
 */
export const editActivityTime = async (chatId, type, oldTime, newTime, amount = null) => {
  const now = dayjs.tz(dayjs(), VIETNAM_TZ);
  const today = now.startOf('day');
  const newDateTime = dayjs.tz(`${today.format('YYYY-MM-DD')} ${newTime}`, VIETNAM_TZ);
  
  if (type === 'feeding') {
    // Tìm feeding record gần nhất hoặc tạo mới với thời gian đã sửa
    await Feeding.create({
      chatId,
      amountMl: amount || 0,
      recordedAt: newDateTime.toDate(),
      note: `Sửa từ ${oldTime || 'không có'}`
    });
    
    // Cập nhật trong routine
    await DailyRoutine.findOneAndUpdate(
      {
        chatId,
        date: { $gte: today.toDate(), $lt: today.add(1, 'day').toDate() }
      },
      {
        $push: {
          feedingSchedule: {
            time: newTime,
            completed: true,
            actualTime: newDateTime.toDate(),
            amountMl: amount || 0,
            missed: false,
            reminded: false
          }
        }
      }
    );
  } else if (type === 'sleep') {
    // Tạo hoặc cập nhật sleep session
    const sleepStart = newDateTime.toDate();
    await SleepSession.create({
      chatId,
      start: sleepStart,
      note: `Sửa từ ${oldTime || 'không có'}`
    });
  }
  
  return true;
};

export default {
  generateVaccinationSchedule,
  getScheduleByAge,
  generateDailyRoutine,
  updateFeedingTime,
  updateSleepTime,
  checkMissedActivities,
  markAsReminded,
  editActivityTime
};
