import mongoose from 'mongoose';

const vaccineSchema = new mongoose.Schema(
  {
    chatId: { type: Number, index: true },
    vaccineName: String,
    date: Date,
    ageMonths: Number, // Độ tuổi tiêm (tháng)
    ageDays: Number, // Độ tuổi tiêm (ngày) - cho vaccine sơ sinh
    required: { type: Boolean, default: true }, // Bắt buộc hay khuyến cáo
    completed: { type: Boolean, default: false }, // Đã tiêm chưa
    completedDate: Date, // Ngày tiêm thực tế
    autoGenerated: { type: Boolean, default: false }, // Tự động tạo từ ngày sinh
    recurring: { type: Boolean, default: false }, // Tiêm nhắc hàng năm (như cúm)
    note: String,
    reminders: {
      pre7d: { type: Boolean, default: false },
      pre3d: { type: Boolean, default: false },
      dayOf: { type: Boolean, default: false }
    }
  },
  { timestamps: true }
);

// Index để tìm nhanh
vaccineSchema.index({ chatId: 1, date: 1 });
vaccineSchema.index({ chatId: 1, completed: 1 });

export const VaccineSchedule = mongoose.model('VaccineSchedule', vaccineSchema);
export default VaccineSchedule;

